services:
  backend:
    build:
      context: .
    restart: always
    ports:
      - "3000:3000"
  influxdb:
    image: influxdb:latest
    volumes:
      - ./influxdb/data:/var/lib/influxdb2:rw
    env_file:
      - .env
    ports:
      - 8086:8086
    restart: unless-stopped
